version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-wayshub
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wayshub
      MYSQL_USER: fauzan
      MYSQL_PASSWORD: devops123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
